---
abstract: 'Colorize your debugger output'
author:
  - "Curtis 'Ovid' Poe <ovid@cpan.org>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DB-Color
provides:
  DB::Color:
    file: lib/DB/Color.pm
    version: 0.08
  DB::Color::Config:
    file: lib/DB/Color/Config.pm
    version: 0.08
  DB::Color::Highlight:
    file: lib/DB/Color/Highlight.pm
    version: 0.08
requires:
  Digest::MD5: 0
  Syntax::Highlight::Engine::Kate: 0.06
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/Ovid/DB--Color
version: 0.08
